// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/fertilizerRecords': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/fertilizerRecords').default>>>>
    }
    '/api/harvestRecords': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/harvestRecords').default>>>>
    }
    '/api/laborRecord': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/laborRecord').default>>>>
    }
    '/api/landPrepRecords': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/landPrepRecords').default>>>>
    }
    '/api/progressRecords': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/progressRecords').default>>>>
    }
    '/api/projects': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/projects').default>>>>
    }
    '/api/sprayingRecords': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sprayingRecords').default>>>>
    }
    '/api/updateStatus': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/updateStatus').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
  }
}
export {}